### ISSUE TITLE
Errors using NPM after fresh installation by NVM4W

### ISSUE THREAD

**Issue by IgalOre** [nvm-windows/nvm#348]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [x] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Installation process will download, install Node.JS and NPM correctly

### Actual Behavior

NPM not downloaded and therefore now installed correctly

### Steps to reproduce the problem:

Just use _nvm install 8.11.1_
Error reported are on attempt to use NPM:
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

When checking in Windows Explorer folder "C:\Program Files\nodejs\node_modules" is empty, were it should have "npm" scripts in them.

I suspect that NPM mirror download https://github.com/npm/npm/archive/ , which is default not correct anymore, when putting in browser it leads to 404 GitHub page.

**Comment by b-dur** [comment]
This could be the same issue as #302 even though the error message isn't exactly the same. The issue however is that npm is not being unzipped and copied correctly to it's destination.
@IgalOre Can you try out some of the suggestions that are mentioned in #302 and see if that helps?

**Comment by IgalOre** [comment]
It do works by using workaround proposed by  @roman-spiridonov . Will write down to do manual patching after installing new version... Oh boy
Thank you @b-dur

**Comment by b-dur** [comment]
@IgalOre Good that you got it working. Hopefully we can get a patched version out soon that will fix this issue.

**Comment by franktopel** [comment]
Half a year later, what is the state of this?

**Comment by b-dur** [comment]
Have you tried latest version?

**Comment by franktopel** [comment]
Sure, guess what brought me here.

**Comment by b-dur** [comment]
To be honest, I gave up trying to get things fixed many months ago. So haven't been following what the status of this project is.

**Comment by renaatdemuynck** [comment]
The NPM repo readme states: 

> This repository is moving to: https://github.com/npm/cli

The last version on the old repo is: `v6.1.0`. So NVM gets a `404` when trying to download `npm-v6.4.1.zip`.

**Comment by jernejk** [comment]
Yes, version 1.1.4 had the issue where the npm download path was incorrect but 1.1.7 seems to be working.

URL used in 1.1.4: https://github.com/npm/npm/releases/tag/v6.4.1
